FROM golang:alpine

RUN apk add --no-cache git
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY migrations /migrations

CMD ["migrate", "-path", "/migrations", "-database", "postgres://postgres:password@db:5432/testdb?sslmode=disable", "up"]